Added flags to echo commands and checking for aws cli configuration

diff --git a/resize_ebs b/resize_ebs
--- a/resize_ebs
+++ b/resize_ebs
@@ -8,40 +8,40 @@ while getopts ":hvSi:s:" opt; do
     case $opt in
         i)
             instanceid=$OPTARG
-            echo "\t Instance-Id: $instanceid"
+            echo -e "\t Instance-Id: $instanceid"
             ;;
         s)
             size=$OPTARG
-            echo "\t Size of New EBS: $size GB"
+            echo -e "\t Size of New EBS: $size GB"
             ;;
         S)
             deleteSnapshot=True
-            echo "\t Deleting snapshot following completion"
+            echo -e "\t Deleting snapshot following completion"
             ;;
         v)
             deleteVolume=True
-            echo "\t Deleting old volume following completion"
+            echo -e "\t Deleting old volume following completion"
             ;;
         h)
             echo "SYNOPSIS"
-            echo "\t sh resize_ebs [vS] -i [instance-id] -s [size]"
-            echo "\n"
+            echo -e "\t sh resize_ebs [vS] -i [instance-id] -s [size]"
+            echo -e "\n"
             echo "DESCRIPTION"
-            echo "\tThe purpose of this script is to resize the root Elastic Block Storage (EBS) of an already running AWS Instance"
-            echo "\n"
+            echo -e "\tThe purpose of this script is to resize the root Elastic Block Storage (EBS) of an already running AWS Instance"
+            echo -e "\n"
             echo "The options are as follows:"
             echo "-i [instance-id]"
-            echo "\t\tSpecifies the Instance ID of the AWS instance to be resized\n"
-            echo "-s [size]"
-            echo "\t\tSpecifies the size, in GB, to resize the EBS to\n"
-            echo "-v\t\tDelete the old volume following the completion of the script\n"
-            echo "-S\t\tDelete the snapshot of the old volume following the completion of the script (You may wish to keep this"
-            echo "\t\tuntil you're sure everything is working as intended)\n"
+            echo -e "\t\tSpecifies the Instance ID of the AWS instance to be resized\n"
+            echo -e "-s [size]"
+            echo -e "\t\tSpecifies the size, in GB, to resize the EBS to\n"
+            echo -e "-v\t\tDelete the old volume following the completion of the script\n"
+            echo -e "-S\t\tDelete the snapshot of the old volume following the completion of the script (You may wish to keep this"
+            echo -e "\t\tuntil you're sure everything is working as intended)\n"
             echo "NOTE"
-            echo "\tThis script assumes you have the AWS CLI tools installed, the instance you wish to resize is running in the same"
-            echo "\tregion as specified in your AWS config file, and that your pem file is stored in ~/.ssh/\n"
-            echo "\tYou may need to alter the permissions of this file to be executable using the following command:"
-            echo "\t\t$ chmod +x resize_ebs"
+            echo -e "\tThis script assumes you have the AWS CLI tools installed, the instance you wish to resize is running in the same"
+            echo -e "\tregion as specified in your AWS config file, and that your pem file is stored in ~/.ssh/\n"
+            echo -e "\tYou may need to alter the permissions of this file to be executable using the following command:"
+            echo -e "\t\t$ chmod +x resize_ebs"
             exit 1
             ;;
         \?)
@@ -49,18 +49,25 @@ while getopts ":hvSi:s:" opt; do
             exit 1
             ;;
         :)
-            echo "\t Option -$OPTARG requires an argument." >&2
+            echo -e "\t Option -$OPTARG requires an argument." >&2
             exit 1
             ;;
     esac
 done
 
 if [ -z ${instanceid+x} ]; then
-    echo "\t Error: You must specify the Instance ID with the -i flag"
+    echo -e "\t Error: You must specify the Instance ID with the -i flag"
     exit 1
 fi
 if [ -z ${size+x} ]; then
-    echo "\t Error: You must specify the size of the new EBS with the -s flag"
+    echo -e "\t Error: You must specify the size of the new EBS with the -s flag"
+    exit 1
+fi
+
+if [ ! -d ~/.aws ]; then
+    echo -e "\tERROR - AWS Configuration not found!"
+    echo -e "Have you installed the AWS CLI tools and set up the configuration?"
+    echo -e "Run 'aws configure' to configure your CLI tools"
     exit 1
 fi
 
@@ -94,6 +101,7 @@ do
 done
 echo "Volume $oldvolumeid detached..."
 
+echo "Creating Snapshot..."
 # Create a snapshot of the original volume
 snapshotid=$(aws ec2 create-snapshot --volume-id $oldvolumeid | jq -r '.SnapshotId')
 while aws ec2 describe-snapshots --snapshot-ids $snapshotid | jq -r '.Snapshots[0].State' | grep -q pending;
@@ -137,17 +145,30 @@ echo "Instance $instanceid started..."
 result=$(aws ec2 describe-instances --instance-ids $instanceid)
 ip=$(echo $result | jq -r '.Reservations[0].Instances[0].PublicIpAddress')
 pem=$(echo $result | jq -r '.Reservations[0].Instances[0].KeyName')
-ssh -i ~/.ssh/$pem.pem ubuntu@$ip 'sudo resize2fs /dev/sda1'
-ssh -i ~/.ssh/$pem.pem ubuntu@$ip 'sudo resize2fs /dev/xvda1'
+
+if [ -f ~/.ssh/$pem.pem ]; then
+    pem="~/.ssh/$pem.pem"
+else
+    echo "ERROR: $pem.pem not located in '~/.ssh'"
+    read -r -p "Please enter full path: " response
+    pem=$response
+fi
+
+ssh -i $pem ubuntu@$ip 'sudo resize2fs /dev/sda1'
+ssh -i $pem ubuntu@$ip 'sudo resize2fs /dev/xvda1'
 
 echo "Done"
 
 # Delete the old volume if -v option is given
 if [ -z "$deleteVolume" ]; then
+    echo "Deleting Volume $oldvolumeid..."
     aws ec2 delete-volume --volume-id $oldvolumeid
+    echo "Done."
 fi
 
 # Delete the created snapshot if -S option is given
 if [ -z "$deleteSnapshot" ]; then
+    echo "Deleting Snapshot $snapshotid..."
     aws ec2 delete-snapshot --snapshot-id $snapshotid
+    echo "Done."
 fi
